# The URL the site will be built for
base_url = "https://skwodo.com"
compile_sass = false
build_search_index = false
minify_html = true

[markdown]
highlight_code = true
external_links_no_referrer = true

[extra]
nav = [
    { path = "/", label = "home", symbol = "#" },
    { path = "/call/", label = "call", symbol = "$" },
    { path = "/blog/", label = "blog", symbol = "%" },
    { path = "/code/", label = "code", symbol = "&" },
]